version: '2.4'

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
    volumes: 
      - './services/users:/usr/share/app'
    ports:
      - 5001:5000
    environment: 
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig